.TH "DIR_" 3 "Thu Mar 28 2019" "File Manager" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DIR_
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBfd\fP"
.br
.ti -1c
.RI "int \fBsize\fP"
.br
.ti -1c
.RI "int \fBidx\fP"
.br
.ti -1c
.RI "struct \fBdirent\fP * \fBfiles\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for File Manager from the source code\&.
