.TH "dirent" 3 "Thu Mar 28 2019" "File Manager" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dirent
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "uint32_t \fBd_ino\fP"
.br
.ti -1c
.RI "int \fBd_type\fP"
.br
.ti -1c
.RI "char \fBd_name\fP [256]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for File Manager from the source code\&.
