.TH "src/fs.c" 3 "Mon Mar 4 2019" "File Manager" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/fs.c \- initializing the partition  

.SH SYNOPSIS
.br
.PP
\fC#include <devutils\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <fcntl\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br

.SH "Detailed Description"
.PP 
initializing the partition 


.PP
\fBAuthor:\fP
.RS 4
ABDELMOUMENE Djahid 
.PP
AYAD Ishak
.RE
.PP
initializing the partition files and utility functions to interact with the os 
.SH "Author"
.PP 
Generated automatically by Doxygen for File Manager from the source code\&.
