.TH "io_filedesc" 3 "Thu Mar 28 2019" "File Manager" \" -*- nroff -*-
.ad l
.nh
.SH NAME
io_filedesc
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBis_allocated\fP"
.br
.ti -1c
.RI "uint32_t \fBoffset\fP"
.br
.ti -1c
.RI "uint32_t \fBmode\fP"
.br
.ti -1c
.RI "uint32_t \fBinodenum\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for File Manager from the source code\&.
