.TH "src/main.c" 3 "Mon Jan 28 2019" "File Manager" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/main.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <manipulation_partition\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.RI "main function "
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBAuthor:\fP
.RS 4
ABDELMOUMENE Djahid 
.PP
AYAD Ishak 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
main function 
.PP
\fBAuthor:\fP
.RS 4
djahid abdelmoumene 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for File Manager from the source code\&.
